name: Node.js CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install Dependencies
        run: |
          cd app
          npm install

      - name: Verify Application
        run: |
          cd app
          npm start &
          sleep 5
          curl http://localhost:3000/health

      - name: Build Docker IMage
        run : |
          cd app
          docker build -t app:ci .

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Tag Docker Image
        run: |
          docker tag app:ci ${{ secrets.DOCKER_HUB_USERNAME }}/autonomous-release-platform:latest

      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKER_HUB_TOKEN }}/autonomous-release-platform:latest

